LogLevel: INFO
MailLevel: INFO
MailAddress: evbuehl@gmail.com
CreationDistance: 24h
RegionCode: DE
Thumbnails:
  Queue: 110N0zGP8Pqwlf_4zz_RdSr9J6JKgTpUM
  Done: 1hot3b2kdLNKxW74xQwiaRPbNVY4pknQb
Template:
  Title: "Gottesdienst der Evangelischen Kirche Bühl | TITLE_DATE | #ekibageistlich"
  Category: People & Blogs
  PlaylistIDs:
    - PLGdIyIZ8SJQq88MQl3gC0Afp2yFcfcpeQ"