name: Build and store binary

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build the go binary
        run: |
          go mod tidy
          go build -ldflags "-s -w" -o ./livestreamScheduler

      - name: Upload binary to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./livestreamScheduler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}