name: Run livestreamScheduler-binary

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:

jobs:
  run-binary:
    runs-on: ubuntu-latest

    steps:

      - name: create credentials.json
        run: echo ${{ secrets.CREDENTIALSJSON }} > credentials.json

      - name: create token.json
        run: echo ${{ secrets.TOKENJSON }} > token.json

      - name: Download binary from GitHub Release
        run: |
          curl -L -o livestreamScheduler https://github.com/evbuehl/livestreamScheduler/releases/latest/download/livestreamScheduler
          chmod +x ./livestreamScheduler

      - name: Execute binary
        run: ./livestreamScheduler