name: Run livestreamScheduler-binary

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: create credentials.json
      id: create-json-credentials
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "credentials.json"
        json: ${{ secrets.CREDENTIALSJSON }}

    - name: create token.json
      id: create-json-token
      uses: jsdaniell/create-json@v1.2.3
      with:
        name: "token.json"
        json: ${{ secrets.TOKENJSON }}

      - name: Download binary from GitHub Release
        run: |
          curl -L -o livestreamScheduler https://github.com/evbuehl/livestreamScheduler/releases/latest/download/livestreamScheduler
          chmod +x ./livestreamScheduler

      - name: Execute binary
        run: ./livestreamScheduler